### ISSUE TITLE
所有的水伤杯子被扫描成了冰伤，其余属性正确。

### ISSUE THREAD

**Issue by qstdnx** [daydreaming666/Amenoma#11]
所有的火伤杯子被扫描成风伤，导出的是genshin optimizer，2.3.1版本

**Comment by daydreaming666** [comment]
请添加更多的描述信息，如系统分辨率、游戏分辨率、显卡型号等。或上传与主程序在同一目录的 Amenoma.log 文件用于分析。

**Comment by qstdnx** [comment]
> 请添加更多的描述信息，如系统分辨率、游戏分辨率、显卡型号等，并上传与主程序在同一目录的 Amenoma.log 文件。

win10版本 21H1 (操作系统内部版本 19043.1237)，系统分辩率为1920*1080，游戏分辨率为1366*768，显卡为gtx870m
[Amenoma.log](https://github.com/daydreaming666/Amenoma/files/7673980/Amenoma.log)

**Comment by daydreaming666** [comment]
尝试下提高分辨率或者提高游戏设置中的画质选项吧，比如换成1600*900, 分辨率低会导致字体模糊而识别错误。
