### ISSUE TITLE
Enhansment Ores are not counted

### ISSUE THREAD

**Issue by Vasilic-Maxim** [daydreaming666/Amenoma#12]
Hi there. I used the latest release (2.3.1) and got the issue of the Enhancement Ores not being counted. By opening this issue, I would like to know if you have any plans to add it. Those materials are already included in [materials list](https://frzyc.github.io/genshin-optimizer/#/doc/MaterialKey) by developers of GOOD format. Thanks in advance for your reply.

**Comment by daydreaming666** [comment]
Cause they are in the end of the `Weapons` list, instead of the `Character Development Item` or `Materials`. I'm thinking about if it is worth it to traverse almost the entire list to scan the three values... 
Maybe it's easier for players to just input them mannually rather than scanning them XD

**Comment by Vasilic-Maxim** [comment]
Sure. You can leave it to players or one more time the software can give us a hand of help. For me, either way, is an option because the software already does a lot. It would be a luxury to have such functionality and I just wanted to know if we will. Anyway, thanks for the last release. It was another great step further to automate all that 'monkey' work to move all our account's data to planers and optimizers. Thanks!
