### ISSUE TITLE
提前停止圣遗物扫描来提升扫描效率

### ISSUE THREAD

**Issue by LittleNightmare** [daydreaming666/Amenoma#14]
据我目测，目前的扫描所有的圣遗物后，再进行过滤导出。但实际上后面大部分扫描是可以省去的，比方说，我勾选了5、4星圣遗物，游戏内圣遗物为品质顺序，这样扫描到三星的圣遗物是就可以停止扫描了。

**Comment by daydreaming666** [comment]
背包里不一定是按星级顺序，也可以按等级顺序。可以扫完自己想要的星级之后按鼠标中键提前停止。

**Comment by LittleNightmare** [comment]
> 

自己按也行吗？我就一个屏幕，每次都自动切到后面了。我觉得要是可以按照星级排序的话，再根据勾选的星级判断能省些时间
