### ISSUE TITLE
Scan not work properly

### ISSUE THREAD

**Issue by Nesishoot** [daydreaming666/Amenoma#15]
Hello

I tried your tool & I followed all step but when I importe file "GOOD" in genshin-center.com/planner, its show wrong number or missed items (show "0")

I put my game in resolution 1600*900 + english language but its dont work correctly, I tried 0.15s but its skip some items or show wrong quantity number

I did something wrong?

Ty for this awesome tool :)

**Comment by daydreaming666** [comment]
The numerical scanning of the material is not so stable by now.
