### ISSUE TITLE
搭建开发环境配置文件没了

### ISSUE THREAD

**Issue by sandboxdream** [daydreaming666/Amenoma#18]
好像是在哪个版本删了?

**Comment by daydreaming666** [comment]
移动到了这里：[https://github.com/daydreaming666/Amenoma/blob/main/model_trainer/dev_env.yml](https://github.com/daydreaming666/Amenoma/blob/main/model_trainer/dev_env.yml)

去除了训练环境和使用环境之间的依赖关系
