### ISSUE TITLE
Number isn't properly read

### ISSUE THREAD

**Issue by Hexatities** [daydreaming666/Amenoma#19]
Hello, have issue on the number recognition. Some of the materials does not have the right amount

Don't know if it will be fixed for 2.4 but submitting just in case, keep up de good work !
[
[Number isn't properly read.zip](https://github.com/daydreaming666/Amenoma/files/7928955/Number.isn.t.properly.read.zip)
](url)

**Comment by daydreaming666** [comment]
The numerical identification of the material is not too stable at this stage.

Duplicated issues, merged with #15
