### ISSUE TITLE
genshin-optimizer JSON format not supported yet

### ISSUE THREAD

**Issue by qwuae1** [daydreaming666/Amenoma#2]
genshin-optimizer默默看了一眼，表示你们没更新JSON 233， format 不一样了
![image](https://user-images.githubusercontent.com/36930393/131226910-d325b51f-24b9-4291-94a4-b9d94b9c69af.png)
![image](https://user-images.githubusercontent.com/36930393/131226921-9feb4ccc-82c9-4837-a6a8-0eb0105168c7.png)
{"version":6,"characterDatabase":{},"artifactDatabase":{"artifact_1":{"id":"artifact_1","setKey":"Berserker","numStars":3,"level":0,"slotKey":"flower","mainStatKey":"hp","substats":[{"key":"","value":0},{"key":"hp_","value":2.5},{"key":"","value":0},{"key":"","value":0}],"location":"","lock":false}},"artifactDisplay":{"filterArtSetKey":"","filterStars":[3,4,5],"filterLevelLow":0,"filterLevelHigh":20,"filterSlotKey":"","filterMainStatKey":"","filterSubstats":["","","",""],"filterLocation":"","filterLocked":"","ascending":false,"sortType":"quality","maxNumArtifactsToDisplay":50,"effFilter":["hp","hp_","atk","atk_","def_","def","eleMas","enerRech_","critRate_","critDMG_"]},"characterDisplay":{},"buildsDisplay":{}}

**Comment by 3096** [comment]
Genshin Optimizer 在做莫娜的导入 https://github.com/frzyc/genshin-optimizer/tree/importer
还请耐心等待一下

**Comment by qwuae1** [comment]
> Genshin Optimizer 在做莫娜的导入 https://github.com/frzyc/genshin-optimizer/tree/importer
> 还请耐心等待一下

你们居然都没睡哈哈哈

**Comment by daydreaming666** [comment]
GO 现在做的导入器是使用的莫娜的格式 ，仓库就在 @3096 那里，还没有合并到主分支上。预计将来将更新支持莫娜格式或使用 GO 专有格式的导入器。

**Comment by daydreaming666** [comment]
Genshin Optimizer 的格式 (GOOD) 现已支持
