### ISSUE TITLE
2.5 scan issue

### ISSUE THREAD

**Issue by nonarygaming** [daydreaming666/Amenoma#23]
Since the update a weird thing is happening. The mouse will go to the first two artifacts and then fail. I am using ver. 2.3.2

**Comment by yufanafuy** [comment]
https://github.com/daydreaming666/Amenoma/issues/22

A fix is being worked on, according to the author.

**Comment by daydreaming666** [comment]
see release [2.5.0](https://github.com/daydreaming666/Amenoma/releases/tag/2.5.0)

**Comment by new2500** [comment]
Hi @daydreaming666 scanning issue in 2.5.0.

> 导入的文件格式不正确(code=Field 'subStat4Type' of variable 'artifactCreateInput' has coerced Null value for NonNull type 'String!')。本功能只能导入由本网站导出的json文件，其他工具来源的json文件若导入出错，请联系相关工具方。
> 导入的文件格式不正确(code=Field 'subStat4Type' of variable 'artifactCreateInput' has coerced Null value for NonNull type 'String!')。本功能只能导入由本网站导出的json文件，其他工具来源的json文件若导入出错，请联系相关工具方。
[artifacts.genmocalc.json.zip](https://github.com/daydreaming666/Amenoma/files/8086248/artifacts.genmocalc.json.zip)

I attached the json file for reproducing.

**Comment by daydreaming666** [comment]
> Hi @daydreaming666 scanning issue in [2.5.0](https://github.com/daydreaming666/Amenoma/releases/tag/2.5.0).
> 
> > 导入的文件格式不正确(code=Field 'subStat4Type' of variable 'artifactCreateInput' has coerced Null value for NonNull type 'String!')。本功能只能导入由本网站导出的json文件，其他工具来源的json文件若导入出错，请联系相关工具方。
> > 导入的文件格式不正确(code=Field 'subStat4Type' of variable 'artifactCreateInput' has coerced Null value for NonNull type 'String!')。本功能只能导入由本网站导出的json文件，其他工具来源的json文件若导入出错，请联系相关工具方。
> 
> [artifacts.genmocalc.json.zip](https://github.com/daydreaming666/Amenoma/files/8086248/artifacts.genmocalc.json.zip)
> 
> I attached the json file for reproducing.


Hi, @new2500 . The Genmo Calculater only supports to import artifacts that has a level 4 ~ 20 and 5 stars. So level 1 artifacts will cause the error.

**Comment by new2500** [comment]
Thx
