### ISSUE TITLE
关于模型训练

### ISSUE THREAD

**Issue by zyr17** [daydreaming666/Amenoma#25]
因为开分支时距离现在的主分支差距过大暂时没有太多精力去merge，就在自己分支上`model_trainer.py`重训模型适配新圣遗物，但是准确度表现不是很好，比较难到99.5%以上，我训了三整轮有两轮最后只能到0.99，而且实测训练结果最好的确实还是偶尔出错。

看到目前版本的天目已经可以识别所有圣遗物和材料了，不知道在训练模型的时候有没有什么trick或者做过改进？

**Comment by daydreaming666** [comment]
[](https://github.com/daydreaming666/Amenoma/commit/59405c347a8cd69930fe22e04cae03813c366707#diff-d3da18545a0248f89475dd90f4573b39f411e820335db1458f02436455767cdf

**Comment by zyr17** [comment]
感谢，我之后研究下看看能不能提升准确率。
