### ISSUE TITLE
Failed to execute script UIMain_EN

### ISSUE THREAD

**Issue by Vasilic-Maxim** [daydreaming666/Amenoma#27]
Hi there. I was exited about new Amenoma release, so I decided to try it out in hopes that it will fix some issues I had in the past. However, insted of doing a propper test I got that message when trying to launch the app. Does anybody experience same trouble?

![Untitled](https://user-images.githubusercontent.com/10743063/161906106-d4b4dfd0-c619-4d47-bc30-4ccec25c953f.png)

**Comment by daydreaming666** [comment]
My bad. Some error happened during the building process. I'll check and fix them soon

**Comment by Vasilic-Maxim** [comment]
Thanks! 🙏

**Comment by daydreaming666** [comment]
Fixed. Everything seems fine by now.

**Comment by Vasilic-Maxim** [comment]
Thanks for your help!
