### ISSUE TITLE
新版本会跳过0级和20级的圣遗物

### ISSUE THREAD

**Issue by tseflcz** [daydreaming666/Amenoma#28]
对于0级和20级的圣遗物会显示[星级等级过滤器] 已跳过，疑似没有等级过滤器加等号？

**Comment by daydreaming666** [comment]
已修复。重新下载即可。

**Comment by tseflcz** [comment]
似乎没修好？还是我下载地址搞错了

**Comment by daydreaming666** [comment]
在这里 [https://github.com/daydreaming666/Amenoma/releases/download/2.6/Amenoma2.6.exe](https://github.com/daydreaming666/Amenoma/releases/download/2.6/Amenoma2.6.exe) 下载就行。

我这里测试可以用的
![屏幕截图 2022-04-11 140813](https://user-images.githubusercontent.com/37444696/162675238-5114e363-1381-415d-9744-0082f09739bb.png)

要是还是不行的话可以附上log我看下， 叫 Amenoma.log， 与程序在同一目录。

**Comment by tseflcz** [comment]
怪不得，现在0级的可以正常保存了，20级的依然会跳过，我扫了前几个看到还是跳过就以为没修好。
[Amenoma.log](https://github.com/daydreaming666/Amenoma/files/8461619/Amenoma.log)

**Comment by tseflcz** [comment]
对了，另外反馈下，这些错误的全都是把8级识别成18，5级识别成15的

**Comment by daydreaming666** [comment]
请问用的是AMD显卡吗？

**Comment by tseflcz** [comment]
不是，是NVIDIA的940MX，不过因为是笔记本显卡比较差就是了

**Comment by xlxl12** [comment]
我也遇到了同样的问题，经过排查是因为分辨率不为1600*900导致的识别错误，请务必检查自己的分辨率是否正确
