### ISSUE TITLE
可以新增扫描背包所有物品和数量的功能吗

### ISSUE THREAD

**Issue by donniean** [daydreaming666/Amenoma#3]
是不是可以跟 https://seelie.inmagi.com/inventory 和 https://genshin-center.com/planner 合作一下，增加一个扫描背包和导入的功能？

**Comment by daydreaming666** [comment]
收到。已列入 todo-list ，请期待下后续版本。

(我先立个 flag 在这

**Comment by daydreaming666** [comment]
做好了~[2.3.0](https://github.com/daydreaming666/Amenoma/releases/tag/2.3.0)
