### ISSUE TITLE
等级过滤功能存在问题

### ISSUE THREAD

**Issue by zzzqh** [daydreaming666/Amenoma#30]
20级的圣遗物会被跳过
1-19级的圣遗物会数值检查失败
只有0级圣遗物正确识别了

设置里等级过滤器是默认的0-20，没有动过

log:
[Amenoma.log](https://github.com/daydreaming666/Amenoma/files/8571388/Amenoma.log)

**Comment by zzzqh** [comment]
似乎和Genshin Launcher Plus 的强制窗口功能有关，用回全屏模式又没问题了

**Comment by DaimonBaby** [comment]
我也是這樣的情況，不過是是用VNC開電腦的，所以不能全屏，而且也不知道這個方法，我是把語言改英文，然後用英文版的就沒問題，反正我電腦端也只用來掃描而已。
