### ISSUE TITLE
Noelle and Geo Traveller Artifacts Scanning (GOOD)

### ISSUE THREAD

**Issue by TLD99** [daydreaming666/Amenoma#33]
When scanning artifacts in GOOD format, Noelle artifacts and Geo Traveller artifacts show inconsistencies.

For example, after scanning my artifacts, here is what my Noelle and Geo Traveler had in-game (Screencaps attached)
Amenoma omits the traveler's artifacts, and Noelle has the incorrect artifacts as well.

Attached the .txt input as well.

![image](https://user-images.githubusercontent.com/102594721/168490094-1fb76f65-910f-4c3e-bc46-b6372a1eb8a2.png)

Please review

![image](https://user-images.githubusercontent.com/102594721/168490004-b8202225-85fb-4a88-af9c-a2674c968b33.png)
![image](https://user-images.githubusercontent.com/102594721/168490022-5736c0ad-2455-4527-9fac-9d06f4614e7b.png)
[artifacts.GOOD.txt](https://github.com/daydreaming666/Amenoma/files/8695754/artifacts.GOOD.txt)

**Comment by TLD99** [comment]
This is my favorite scanner, please let me know if I can do anything to sort this issue out

**Comment by qwqllh** [comment]
Thanks for reporting, but the maintainer is currently working on his final exam. Maybe he will fix these problems after that.

**Comment by TLD99** [comment]
Think it's sorted with the latest release. Will reopen if it's still occurring
