### ISSUE TITLE
App refuses to capture window

### ISSUE THREAD

**Issue by GeometricalTaco** [daydreaming666/Amenoma#47]
In both the artifact and the material tabs, it returns the message:
"Trying to capture the window...
Capture window failed."
I have tried all the available resolutions, and restarted both Genshin and Amenoma but it still doesn't work, I even re-downloaded Amenoma. It has worked in the past, I don't think I've changed anything since I last used it.
Any idea what's up?
Will gladly provide any information I can

**Comment by daydreaming666** [comment]
I will try fixing it in the next update in 20 days. Recently I'm busy working on Chinese Postgraduate Exam. Thank you for your feedback :)

**Comment by GeometricalTaco** [comment]
All good, good luck for your exams!

**Comment by aestilog** [comment]
Is the window title correct?
![image](https://user-images.githubusercontent.com/37444696/216488198-d1e418ea-8e36-4250-a9be-6ccfde686653.png)
The App try to find a window named "Genshin Impact" when running `Capture Window`

**Comment by GeometricalTaco** [comment]
I can't fully remember what happened after I submitted the issue, but I think I restarted various things and re-tried, which seemed to fix the issue. It hasn't happened since, so all I can really say is that it was a weird rare bug

**Comment by aestilog** [comment]
okay! Just comment when you caught it again. Have a nice day!
