### ISSUE TITLE
应该如何缩减打包后文件的体积

### ISSUE THREAD

**Issue by zyr17** [daydreaming666/Amenoma#5]
我正在基于您的代码做二次开发，发现使用开发配置和build脚本得到的结果有500MB以上，和您提供的100MB出头的大小有很大偏差，请问您用于打包的环境有做过什么调整吗？应该怎么减小打包体积

**Comment by daydreaming666** [comment]
使用 [ArtScanner/build_env_ui.yml](https://github.com/daydreaming666/Amenoma/blob/main/ArtScanner/build_env_ui.yml) 来生成exe包。
[/ArtScanner/Tools/model_trainer/dev_env.yml](https://github.com/daydreaming666/Amenoma/blob/main/ArtScanner/Tools/model_trainer/dev_env.yml) 环境仅用于图片处理研究与模型训练。

**Comment by zyr17** [comment]
明白了，确实小了很多，谢谢。
