### ISSUE TITLE
Equipped Artifacts' location incorrect, adds them to "Eula" instead of "Layla"

### ISSUE THREAD

**Issue by Hurric4ne** [daydreaming666/Amenoma#50]
After scanning, Artifacts that are equipped on **Layla** are equipped on **Eula** instead (which i do not even own).
The scan was done with AmenomaEN v.30.2

I've added the exported json file (changed to a .txt file since o can't upload the .json file)
[artifacts.GOOD.txt](https://github.com/daydreaming666/Amenoma/files/10366084/artifacts.GOOD.txt), but here is an example from the file aswell:
`{
         "setKey":"WanderersTroupe",
         "slotKey":"circlet",
         "level":8,
         "rarity":5,
         "mainStatKey":"hp_",
         "location":"Eula",
         "lock":false,
         "substats":[
            {
               "key":"enerRech_",
               "value":11.0
            },
            {
               "key":"hp",
               "value":209
            },
            {
               "key":"critRate_",
               "value":3.1
            },
            {
               "key":"atk_",
               "value":8.7
            }
         ]
      },`

When uploading the file on Genshin Optimizer, it then incorrectly adds **Eula** as one of my Characters instead of **Layla**.

**Comment by Hurric4ne** [comment]
I've also found the following info on the Amenomona.log file:
`[   INFO] 2023-01-04 18:50:40,488 / UIMain_EN[947]	/Detected info: {'equipped': 'Euipped: Tarlba', 'level': '+0', 'main_attr_name': 'ATK', 'main_attr_value': '47', 'name': "Bard's Arrow Feather", 'subattr_1': 'HP+299', 'subattr_2': 'HP+5.8%', 'subattr_3': 'Energy Recharge+6.5%', 'type': 'Plume of Death', 'star': 5, 'locked': False}
[   INFO] 2023-01-04 18:50:40,488 /     utils[236]	/Corrected character from [Euipped: Tarlba] to [Eula] with distance 3
[   INFO] 2023-01-04 18:50:40,488 / UIMain_EN[370]	/Info message shown. msg=Detected [Bard's Arrow Feather]
[Uploading Amenoma.log…]()
`

**Comment by daydreaming666** [comment]
Layla have not added to the character list of Amenoma yet. Please wait for the new version(in progress).

**Comment by Hurric4ne** [comment]
Sure, no problem. I just wanted to inform you about the issue.
Have a nice day!

**Comment by aestilog** [comment]
fixed in v3.4
